### ISSUE TITLE
If not using start_print macro, can that step be safely skipped?

### ISSUE THREAD

**Issue by GhostlyCrowd** [Turge08/print_area_bed_mesh#10]
As the title asks, is it appropriate to skip that set if  I do not use a start macro, I let the slicer handle all start gcode functions.

**Comment by RedGuilhas** [comment]
> You can put the bed_mesh_calibrate command in the printer start gcode. Let me know if you need help with the syntax.

I need help with the syntax please.

Thanks

**Comment by Turge08** [comment]
Try this:

PrusaSlicer/SuperSlicer:
<pre>BED_MESH_CALIBRATE PRINT_MIN={first_layer_print_min[0]},{first_layer_print_min[1]} PRINT_MAX={first_layer_print_max[0]},{first_layer_print_max[1]}</pre>

Cura:
<pre>BED_MESH_CALIBRATE PRINT_MIN=%MINX%,%MINY% PRINT_MAX=%MAXX%,%MAXY%</pre>

**Comment by RedGuilhas** [comment]
Thanks it worked!
