### ISSUE TITLE
Printing without a MESH if cleared

### ISSUE THREAD

**Issue by WickedInvi** [Turge08/print_area_bed_mesh#11]
My cancel and end print have BED_MESH_CLEAR. Once it's cleared and a new print starts it says the mesh is the same size or smaller but it's not showing the MESH.

**Comment by Turge08** [comment]
@WickedInvi Did it resolve your issue?

**Comment by WickedInvi** [comment]
I don't have an issue with this as I mesh every time with the ```FORCE_NEW_MESH=True!``` However I would suggest that this needs to be fixed if possible to avoid issues for others.

Not sure how it works as it checks the previous mesh size but if it's been cleared should mesh again.

**Comment by Turge08** [comment]
@WickedInvi Like I said, it should be fixed now.
