### ISSUE TITLE
[Future request] Probe before every print

### ISSUE THREAD

**Issue by WickedInvi** [Turge08/print_area_bed_mesh#12]
Can you make an option to always probe despite what mesh is active?

**Comment by Turge08** [comment]
Try adding the parameter FORCE_NEW_MESH=True after PRINT_MAX in your slicer gcode

**Comment by Turge08** [comment]
@WickedInvi Let me know if this works for you.

**Comment by WickedInvi** [comment]
Not working.

15:02:45 
// print_min: 100.911,94.9121
15:02:45 
// print_max: 129.086,123.088
15:02:45 
// last_bed_mesh: 96.5637,90.5644 133.437,127.433
15:02:45 
// No need to recreate Bed Mesh since it's same as current mesh or smaller

**Comment by Turge08** [comment]
Sorry, should've been in your print_start macro:

<pre>BED_MESH_CALIBRATE PRINT_MIN={params.PRINT_MIN} PRINT_MAX={params.PRINT_MAX} FORCE_NEW_MESH=True</pre>

**Comment by WickedInvi** [comment]
It's working now
