### ISSUE TITLE
Probing a small area front left of the bed. PRINT_MIN/MAX issue. 

### ISSUE THREAD

**Issue by WickedInvi** [Turge08/print_area_bed_mesh#14]
Getting a problem with a small patch on the front left of the bed. Using SuperSlicer.

```
15:52:52 
// print_min: -34.0422,-39.6127
15:52:52 
// print_max: 34.0422,34.0422
15:52:52 
// mesh_min: 25,25
15:52:52 
// mesh_max: 54.0422,54.0422
15:52:52 
// probe_count: 5,5
15:52:52 
// relative_reference_index: 12
15:52:52 
// Generating new points...
15:52:52 
// bed_mesh: generated points
// Index | Tool Adjusted | Probe
```
![image](https://user-images.githubusercontent.com/49752323/145050748-b14935dd-13c8-4644-9640-6388bf895bd9.png)

**Comment by Turge08** [comment]
I had a typo in the command in the slicer start gcode. Can you try updating it with the one from the Read Me?

<pre>PRINT_MIN={first_layer_print_min[0]},{first_layer_print_min[1]} PRINT_MAX={first_layer_print_max[0]},{first_layer_print_max[1]}</pre>

**Comment by WickedInvi** [comment]
Works fine now.
