### ISSUE TITLE
Klipper allows a scalar to be used as the Bed_Mesh probe count - causes undefined error

### ISSUE THREAD

**Issue by shortbus** [Turge08/print_area_bed_mesh#3]
Klipper allows the use of a scalar AND the use of a pair for the mesh. Example:

[bed_mesh]
probe_count: 5

From the Klipper docs:
"The number of points to probe on each axis, specified as x,y integer values. In this example 5 points will be probed along the X axis, with 3 points along the Y axis, for a total of 15 probed points. **Note that if you wanted a square grid, for example 3x3, this could be specified as a single integer value that is used for both axes**, ie probe_count: 3. Note that a mesh requires a minimum probe_count of 3 along each axis."

This causes an:
`"Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': UndefinedError: list object has no element 1"`

_The fix is here:_
Replace this line:
`{% set probe_count_y = bedMeshConfig.probe_count.split(",")[1]|int %}`

With this line:
```
{% if bedMeshConfig.probe_count.split(",")[1] is defined %}
    {% set probe_count_y = bedMeshConfig.probe_count.split(",")[1]|int %}
{% else %}
    {% set probe_count_y = probe_count_x %}
{% endif %}
```

The X portion works fine, but we need to check to see if the Y portion is undefined, if so, then set probe_count_y equal to probe_count_x.

**Comment by Turge08** [comment]
Thanks @shortbus! It's fixed now.
